// <auto-generated />
using Kolos2_3tabele.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolos2_3tabele.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20240607130239_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolos2_3tabele.Entities.Muzyk", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMuzyk"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Pseudonim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMuzyk")
                        .HasName("IdMuzyk");

                    b.ToTable("Muzyk", (string)null);

                    b.HasData(
                        new
                        {
                            IdMuzyk = 1,
                            Imie = "Adam",
                            Nazwisko = "Nowak",
                            Pseudonim = "AdNo"
                        },
                        new
                        {
                            IdMuzyk = 2,
                            Imie = "Alicja",
                            Nazwisko = "Malinowska"
                        });
                });

            modelBuilder.Entity("Kolos2_3tabele.Entities.Utwor", b =>
                {
                    b.Property<int>("IdUtwor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtwor"));

                    b.Property<float>("CzasTrwania")
                        .HasColumnType("real");

                    b.Property<string>("NazwaUtworu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUtwor")
                        .HasName("IdUtwor");

                    b.ToTable("Utwor", (string)null);

                    b.HasData(
                        new
                        {
                            IdUtwor = 1,
                            CzasTrwania = 2.2f,
                            NazwaUtworu = "autor1utwor1"
                        },
                        new
                        {
                            IdUtwor = 2,
                            CzasTrwania = 3.42f,
                            NazwaUtworu = "autor1utwor2"
                        },
                        new
                        {
                            IdUtwor = 3,
                            CzasTrwania = 5.5f,
                            NazwaUtworu = "autor2utwor1"
                        });
                });

            modelBuilder.Entity("WykonawcaUtworu", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .HasColumnType("int");

                    b.Property<int>("IdUtwor")
                        .HasColumnType("int");

                    b.HasKey("IdMuzyk", "IdUtwor");

                    b.HasIndex("IdUtwor");

                    b.ToTable("WykonawcaUtworu");

                    b.HasData(
                        new
                        {
                            IdMuzyk = 1,
                            IdUtwor = 1
                        },
                        new
                        {
                            IdMuzyk = 1,
                            IdUtwor = 2
                        },
                        new
                        {
                            IdMuzyk = 2,
                            IdUtwor = 3
                        });
                });

            modelBuilder.Entity("WykonawcaUtworu", b =>
                {
                    b.HasOne("Kolos2_3tabele.Entities.Muzyk", null)
                        .WithMany()
                        .HasForeignKey("IdMuzyk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos2_3tabele.Entities.Utwor", null)
                        .WithMany()
                        .HasForeignKey("IdUtwor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
